name: Deploy MERN Koperasi to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        run: npm install
        working-directory: ./client
        
      - name: Build React Frontend
        run: npm run build
        working-directory: ./client
      
      - name: Deploy to EC2 with rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: "./" 
          remote_path: "/home/${{ secrets.EC2_USER }}/app-staging/"

      - name: Run deployment scripts on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Menghentikan layanan yang sedang berjalan
            pm2 stop mern-koperasi-backend || true
            pm2 delete mern-koperasi-backend || true
            
            # Menghapus file lama di Nginx
            sudo rm -rf /var/www/html/*
            
            # Menyalin file baru dari staging ke tempat yang benar
            sudo cp -r /home/${{ secrets.EC2_USER }}/app-staging/client/dist/. /var/www/html/
            
            # Mengganti URL server di konfigurasi frontend
            sudo sed -i "s|VITE_SERVER_URL=\"http://localhost:5173\"|VITE_SERVER_URL=\"http://${{ secrets.EC2_HOST }}:5000\"|g" /var/www/html/assets/conf.js
            
            # Menjalankan backend
            cd /home/${{ secrets.EC2_USER }}/app-staging/server
            npm install --production
            pm2 start index.js --name "mern-koperasi-backend"
            
            # Menyimpan konfigurasi PM2
            pm2 save --force
            
            # Membersihkan folder staging
            sudo rm -rf /home/${{ secrets.EC2_USER }}/app-staging
