name: Deploy MERN Koperasi to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Menghentikan layanan yang sedang berjalan jika ada
            pm2 stop mern-koperasi-backend || true
            pm2 delete mern-koperasi-backend || true

            # Hapus folder staging jika sudah ada dan buat yang baru
            sudo rm -rf /home/${{ secrets.EC2_USER }}/app-staging
            mkdir -p /home/${{ secrets.EC2_USER }}/app-staging
            
            # Menggunakan git untuk kloning repositori ke folder staging
            git clone --branch main --single-branch https://github.com/${{ github.repository }}.git /home/${{ secrets.EC2_USER }}/app-staging
            
            # Menjalankan instalasi dependensi backend
            cd /home/${{ secrets.EC2_USER }}/app-staging/server
            npm install --production
            
            # Menjalankan instalasi dan build frontend
            cd /home/${{ secrets.EC2_USER }}/app-staging/client
            npm install
            npm run build
            
            # Hapus konten lama di Nginx
            sudo rm -rf /var/www/html/*
            
            # Salin file frontend yang sudah dibuild ke direktori Nginx
            sudo cp -r /home/${{ secrets.EC2_USER }}/app-staging/client/dist/. /var/www/html/
            
            # Mengganti URL server di konfigurasi frontend yang sudah di-deploy
            if [ -f "/var/www/html/assets/conf.js" ]; then
              sudo sed -i "s|VITE_SERVER_URL=\"http://localhost:5000/\"|VITE_SERVER_URL=\"http://${{ secrets.EC2_HOST }}/\"|g" /var/www/html/assets/conf.js
            else
              echo "Warning: /var/www/html/assets/conf.js not found. Skipping sed command."
            fi
            
            # Jalankan backend dengan PM2
            cd /home/${{ secrets.EC2_USER }}/app-staging/server
            pm2 start index.js --name "mern-koperasi-backend"
            
            # Simpan konfigurasi PM2 agar aplikasi otomatis berjalan saat server reboot
            pm2 save --force
