name: Deploy MERN Koperasi to AWS EC2

on:
  # Ini akan menjalankan workflow setiap kali ada push ke branch 'main'
  push:
    branches:
      - main
  
  # Ini akan menambahkan tombol "Run workflow" di GitHub Actions
  # Jadi kamu bisa jalankan deployment secara manual tanpa perlu push
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        run: npm install
        working-directory: ./client
        
      - name: Build React Frontend
        run: npm run build
        working-directory: ./client

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Menghentikan proses aplikasi yang sedang berjalan
            pm2 stop mern-koperasi-backend || true
            pm2 stop mern-koperasi-frontend || true
            
            # Menghapus file lama di server EC2
            rm -rf /var/www/html/*
            rm -rf /home/ubuntu/mern-koperasi-server-temp
            
            # Menyalin file frontend yang sudah dibuild dari GitHub Actions ke EC2
            scp -r ./client/dist/* /var/www/html/
            
            # Menyalin seluruh folder server
            scp -r ./server /home/ubuntu/mern-koperasi-server-temp
            
            # Ganti server_url di konfigurasi frontend
            # Ini penting agar frontend tahu alamat backendnya
            sed -i 's|VITE_SERVER_URL="http://localhost:5173"|VITE_SERVER_URL="http://${{ secrets.EC2_HOST }}:5000"|g' /var/www/html/assets/conf.js
            
            # Jalankan backend
            cd /home/ubuntu/mern-koperasi-server-temp
            # Menggunakan PM2 untuk menjaga aplikasi backend tetap berjalan
            pm2 start index.js --name "mern-koperasi-backend"
            
            pm2 save
